### ISSUE TITLE
rpcx 不支持 etcd v3，注册的service显示不出来

### ISSUE THREAD

**Issue by harryzzp** [smallnest/rpcx-ui#3]
测试环境：
etcd Version: 3.2.0-rc.0
Git SHA: 7e6d876
Go Version: go1.8.1
Go OS/Arch: linux/amd64

我试了下rpcx-ui对zookeeper和etcdv3的监控rpcx服务，测试服务代码用的是：
https://github.com/harryzzp/rpcx-examples2/tree/master/zookeeper_registry
https://github.com/rpcx-ecosystem/rpcx-examples2/tree/master/etcdv3_registry
zk可以正常监控到services，但是etcdv3不能正常监控。

**Comment by smallnest** [comment]
如果你运行 https://github.com/rpcx-ecosystem/rpcx-examples2/tree/master/etcdv3_registry 中的例子，可以正常工作，我的etcd是 3.1.8, Go: 1.8.1, OS" darwin。

但是rpcx-ui却显示不出来注册的service，这是一个问题。

可能rpcx-ui需要使用v3的API，我会在将来的时间更新，也欢迎pull request

**Comment by tungh** [comment]
etcd一样的问题，期待早日更新！
etcd Version: 3.2.2
Git SHA: 81fa822 
Go Version: go1.8.3
Go OS/Arch: daewin/amd64

**Comment by smallnest** [comment]
fixed
