### ISSUE TITLE
使用etcd的问题

### ISSUE THREAD

**Issue by icyfire** [smallnest/rpcx-ui#8]
etcd已正常启动，服务端和客户端也能正常注册服务和发现服务。但是rpcx-ui上无法加载服务列表，报如下错误：

```
2020/01/15 14:45:09 failed to list services /rpcx/: client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookup http: no such host
```

**Comment by smallnest** [comment]
看起来rpcx-ui无法连接etcd。
贴一下你的rpcx-ui的配置文件。

以及你的etcd的版本。

当前的rpcx-ui只支持etcd v2 api.

**Comment by icyfire** [comment]
> 看起来rpcx-ui无法连接etcd。
> 贴一下你的rpcx-ui的配置文件。
> 
> 以及你的etcd的版本。
> 
> 当前的rpcx-ui只支持etcd v2 api.

那有可能是版本问题了。

`config.json`：

```
{
	"registry_type": "etcd",
	"registry_url": "http://localhost:2379",
	"service_base_url": "/rpcx",
	"host": "127.0.0.1",
	"port": 8972,
	"user": "admin",
	"password": "admin"
}
```
etcd版本`v3.4.0`，使用`-enable-v2=true`进行启动。

**Comment by smallnest** [comment]
我测试了一下，应该是配置中格式设置错误。你把 etcd配置文件中的那个`http://`去掉就好了。

<img width="313" alt="image" src="https://user-images.githubusercontent.com/865763/72418526-f5c29600-37b5-11ea-9c95-8c287ba36632.png">

**Comment by icyfire** [comment]
> 我测试了一下，应该是配置中格式设置错误。你把 etcd配置文件中的那个`http://`去掉就好了。
> 
> <img alt="image" width="313" src="https://user-images.githubusercontent.com/865763/72418526-f5c29600-37b5-11ea-9c95-8c287ba36632.png">

可以了，感谢
